### PR TITLE
Configurable default matchers

### PR DESCRIPTION
**Pull request by MartinMystikJonas**

### CODE REVIEW

**Comment by davedevelopment** [comment]
Sorry for the delay. Please could you add a note to the changelog and I'll get this merged, thank you.

**Comment by MartinMystikJonas** [comment]
@davedevelopment Should I add 1.4.4 version header without date and put it under  it or just add bulltpoint at the begginning of changelog?

**Comment by davedevelopment** [comment]
Hi @MartinMystikJonas, I just merged #1133 which has a heading, so if you want to rebase and then just add a bullet point, that would be great. 

I just wanted to say thank you for this as well, it's a really nice little feature :raised_hands:

**Comment by MartinMystikJonas** [comment]
@davedevelopment Ok changelog entry added. I am glad I can help to improve mockery.

**Comment by davedevelopment** [comment]
Thank you :tada:

**Pull request merged**
