### PR TITLE
Add method that allows defining a set of arguments the mock should yield

### LINKED ISSUE #520: No way to mock methods returning generators
There should be a way to mock methods that return generators, i.e. `MockInterface::andYield($foo, $bar, ...)`.

### PR DESCRIPTION
**Pull request by Blacksmoke16**
Resolves #520

### CODE REVIEW

**Comment by davedevelopment** [comment]
Please could you add a note to the changelog and I'll get this merged.

**Comment by Blacksmoke16** [comment]
@davedevelopment Do you want it to be a specific version/date or with like question marks as placeholders for now?

**Comment by davedevelopment** [comment]
Sorry, didn't realise we didn't have a heading yet. Yes and no, something like this would be great :)

``` markdown
# 1.4.4 (TBC)

- Summary of your change
```

**Comment by Blacksmoke16** [comment]
@davedevelopment Done.

**Pull request merged**
