### PR TITLE
splitted TestListenerTrait if checks

### PR DESCRIPTION
**Pull request by prisis**
see https://github.com/mockery/mockery/pull/903#issuecomment-424665793

### CODE REVIEW

**Comment by prisis** [comment]
@rcwsr can you try this?

**Comment by rcwsr** [comment]
I get this:

```
PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Mockery\Adapter\Phpunit\Legacy\TestListenerTrait::endTest() must be an instance of PHPUnit\Framework\Test, instance of App\SomeTest given, called in /.../vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/Legacy/TestListenerForV5.php on line 37 and defined in /.../vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/Legacy/TestListenerTrait.php:50
```

**Comment by prisis** [comment]
can you show me your test?

**Comment by GrahamCampbell** [comment]
What's the status with this PR?

**Comment by davedevelopment** [comment]
@GrahamCampbell ugh, sorry, I left them to discuss and I guess it didn't get anywhere. I think it's no longer needed due to #947, but if I'm honest I haven't got time to be investigating PHPUnit 5.7.* issues :man_shrugging:

**Pull request closed without merging**
