### PR TITLE
Add mockery_callSubjectMethod method to interface

### PR DESCRIPTION
**Pull request by dciancu**
Add mockery_callSubjectMethod method to interface - for autocompletion in smart IDEs.

### CODE REVIEW

**Comment by davedevelopment** [comment]
Adding to the interface needs to be done lightly and I don't think we can do this just to support IDEs.

**Comment by dciancu** [comment]
@davedevelopment Thanks for the reply.
Can you please elaborate? Should I write some tests for this method?

**Comment by davedevelopment** [comment]
@dciancu sorry for the late reply, I must have missed this. 

If we add methods to the interface, we break backwards compatibility, so ideally we'd to tag a new major version.

**Comment by dciancu** [comment]
Thanks for the reply Dave, I understand now.
Well, I use this method quite a lot in my tests. I set expectations and then use this method to call the real method behind the mock that I want to test and my IDE was always warning me about this method not being present on the interface.
I thought it is worth adding it to the interface.
We can do it in the next major version then.

**Comment by davedevelopment** [comment]
@dciancu Can you share an example?

**Comment by dciancu** [comment]
Here you go:
```php
    public function testRepository()
    {
        $store = m::mock(Store::class);
        $app = m::mock(Application::class);
        $manager = m::mock(CacheManager::class, [$app]);
        $dispatcher = m::mock(EventsDispatcher::class);

        $app->shouldReceive('bound')->twice()->with(EventsDispatcher::class)->andReturn(false, true);
        $app->shouldReceive('make')->once()->with(EventsDispatcher::class)->andReturn($dispatcher);

        $repository = $manager->mockery_callSubjectMethod('repository', [$store]);

        $this->assertInstanceOf(Repository::class, $repository);
        $this->assertEquals($store, $repository->getStore());

        $manager->mockery_callSubjectMethod('repository', [$store]);
    }
```

**Comment by dciancu** [comment]
In the above example I could have just created a new CacheManager class.
Here is another one which calls itself:
```php
    public function testTooManyAttempts()
    {
        $limiter = m::mock(RateLimiter::class);

        $limiter->shouldReceive('retriesLeft')->times(3)->with('test', 5)->andReturn(5, 0);
        $limiter->shouldReceive('availableIn')->twice()->with('test')->andReturn(100, 0);
        $limiter->shouldReceive('resetAttempts')->once()->with('test');

        $this->assertEquals(['status' => false, 'retries_left' => 5],
            $limiter->mockery_callSubjectMethod('tooManyAttempts', ['test', 5])
        );
        $this->assertEquals(['status' => true, 'available_in' => 100],
            $limiter->mockery_callSubjectMethod('tooManyAttempts', ['test', 5])
        );
        $this->assertEquals(['status' => false, 'retries_left' => 5],
            $limiter->mockery_callSubjectMethod('tooManyAttempts', ['test', 5])
        );
    }
```

**Comment by davedevelopment** [comment]
Ah, the second example is much easier to see. I typed this out anyway, note the use of the `passthru()` method.

``` php
<?php

require "vendor/autoload.php";

use Mockery as m;
Mockery::setLoader(new Mockery\Loader\RequireLoader(sys_get_temp_dir()));

class Store { }
class Application {
    function bound($class) {}
    function make($class) {}
}
class CacheManager {
    function __construct(Application $app) { $this->app = $app; }
    function repository(Store $store): Repository {
        $this->app->bound(EventsDispatcher::class);
        $this->app->bound(EventsDispatcher::class);
        $this->app->make(EventsDispatcher::class);
        return new Repository($store);
    }
}
class EventsDispatcher { }

class Repository {
    function __construct(Store $store) { $this->store = $store; }
    function getStore(): Store { return $this->store; }
}

$store = m::mock(Store::class);
$app = m::mock(Application::class);
$manager = m::mock(CacheManager::class, [$app]);
$dispatcher = m::mock(EventsDispatcher::class);

$app->shouldReceive('bound')->twice()->with(EventsDispatcher::class)->andReturn(false, true);
$app->shouldReceive('make')->once()->with(EventsDispatcher::class)->andReturn($dispatcher);

$manager->allows()->repository($store)->passthru();

//$repository = $manager->mockery_callSubjectMethod('repository', [$store]);
$repository = $manager->repository($store);

var_dump($repository instanceof Repository);
var_dump($store == $repository->getStore());

```

Would that be what you want to achieve?

**Comment by davedevelopment** [comment]
Similarly with the second example

``` php
        $limiter = m::mock(RateLimiter::class);

        $limiter->shouldReceive('retriesLeft')->times(3)->with('test', 5)->andReturn(5, 0);
        $limiter->shouldReceive('availableIn')->twice()->with('test')->andReturn(100, 0);
        $limiter->shouldReceive('resetAttempts')->once()->with('test');

        $limiter->allows()->tooManyAttempts(anyArgs())->passthru();

        $this->assertEquals(['status' => false, 'retries_left' => 5],
            $limiter->tooManyAttempts('test', 5)
        );
        $this->assertEquals(['status' => true, 'available_in' => 100],
            $limiter->tooManyAttempts('test', 5)
        );
        $this->assertEquals(['status' => false, 'retries_left' => 5],
            $limiter->tooManyAttempts('test', 5)
        );
```

**Comment by dciancu** [comment]
Thank you for taking the time to look into this, I did not know `passthru()` can be used like this, I will rewrite my tests.
Thanks for Mockery, Dave, you rock 🤘

**Comment by dciancu** [comment]
Hi Dave, I am reaching out to you in regards to the above conversation, any idea how may I test this?

```php
$command = m::mock(PendingCommand::class);

$command->shouldReceive('run')->once()->withNoArgs()->andReturnUsing(function () use ($command) {
    $command->hasExecuted = true;
});
$command->allows('__destruct')->passthru();

$command->__destruct();
$command->__destruct();
// $command->mockery_callSubjectMethod('__destruct', []);
// $command->mockery_callSubjectMethod('__destruct', []);
```
The above calls the Mockery class destructor instead of the original class one (the `__construct` method work fine with the above code).
Thank you very much!

**Comment by davedevelopment** [comment]
@dciancu I think mockery will only allow that if you pass some arguments in so that the original constructor is called.

``` php
$command = m::mock(PendingCommand::class, [$ctorArg1, $ctorArg2]);
```

I'm not 100% sure on the reasoning, I just seem to remember that's what got implemented.

**Pull request closed without merging**
