### PR TITLE
Fix TestListener for php 6 version.

### PR DESCRIPTION
**Pull request by bruli**

### CODE REVIEW

**Comment by davedevelopment** [comment]
Will take a look at this next week, my preference would be to continue supporting PHPUnit 5 alongside 6 for the time being.

**Comment by pavarnos** [comment]
Will there be a mockery release soon? I'd like to migrate to phpunit 6 but can not until mockery is compatible...

**Comment by davedevelopment** [comment]
My understanding is the master branch should now support PHPUnit 5 + 6, I don't know when there will be a release.

**Comment by pavarnos** [comment]
The mockery TestListener adapter uses the old _ class name rather than the new namespaces?

**Comment by davedevelopment** [comment]
My mistake! I didn't realise this was for the test listener - reopened. Regardless, the test listener shouldn't be a blocker for using PHPUnit 6, the test listener itself no longer functions properly and you should use the `MockeryTestCase` base class or the trait to manage the tear down.

**Comment by pavarnos** [comment]
Can there be some kind of cross check added to protect you from forgetting to inherit from MockeryTestCase or use the trait (eg when migrating a large collection of tests from the Listener as you suggest above)

So maybe a project test bootstrap file could call `Mockery::usingPhpUnit()` and throw an exception if `Mockery::close()` is not called by the time `endTest()` is called in the test listener?

**Comment by spdionis** [comment]
Why doesn't the test listener function properly? I liked this option best for the integration. Is it not possible to update it?

**Comment by davedevelopment** [comment]
@spdionis heya, it was discussed here #376 (which you opened) and sebastianbergmann/phpunit#1440

**Comment by spdionis** [comment]
@davedevelopment hey, right, I forgot about that discussion, it was quite a while ago :). Apparently we'll have to use trait or base class after all.

**Comment by theofidry** [comment]
What is the status for this PR?

**Comment by davedevelopment** [comment]
@theofidry a mess?!

The listener can't support both PHPUnit 6 and 5.7, unless we have separate class definitions. PHPUnit 5.7 has a forward compatibility layer, but it only goes so far. We can't specify one class that is compatible with PHPUnit 5.7's `PHPUnit_Framework_TestListener` and PHPUnit 6's `PHPUnit\Framework\TestListener`.

Giving the listener isn't essential to development (it's only a fail safe now, you need to use the trait or base class), perhaps we should just drop support for the listener in PHPUnit 5.7? What do people think?

**Comment by theofidry** [comment]
Hm dropping the listener is a bit of an issue, we are using it for Humbug and Infection is missing some tests due to the lack of support for PHPUnit 6 for it.

I would rather suggest to drop PHPUnit 5.* support completely and move forward. It's not like Mockery is gonna disappear for people stuck on PHPUnit 5.*.

**Comment by davedevelopment** [comment]
> I would rather suggest to drop PHPUnit 5.* support completely and move forward. It's not like Mockery is gonna disappear for people stuck on PHPUnit 5.*.

That's true, but we're so close to a 1.0 that does support 5.7, I'd rather not throw it all away. I think I'll make the listener PHPUnit 6 only, but keep support for everything else.

**Comment by theofidry** [comment]
That would be an acceptable compromise

**Comment by davedevelopment** [comment]
Closing in favour of #786

**Pull request closed without merging**
