### PR TITLE
Fixes #850 for PHPUnit 5/6/7 compatibilities

### LINKED ISSUE #850: Mockery is not compatible with phpunit 7.0
> The `PHPUnit\Framework\BaseTestListener` class has been removed, it was deprecated since PHPUnit 6.4. Please use the `PHPUnit\Framework\TestListenerDefaultImplementation instead`.

### PR DESCRIPTION
**Pull request by prisis**
Thx for the first try @barryvdh

### CODE REVIEW

**Comment by patrickarnold79** [comment]
Thanks @prisis, facing the same issues you are addressing here.

**Comment by davedevelopment** [comment]
I think this looks ok, are all of the changes necessary for the PHPUnit compatibility or was some of it tidying up?

**Comment by prisis** [comment]
All of them are necessary, phpunit added a validator, so i had to remove some keys

**Comment by borNfreee** [comment]
when are going to release this @davedevelopment?

**Comment by rcwsr** [comment]
I still get this error with these dependencies:

```
        "phpunit/phpunit": "~5.7",
        "mockery/mockery": "dev-master",
```

```
PHP Fatal error:  Uncaught Error: Class 'PHPUnit\Util\Blacklist' not found in /.../vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/Legacy/TestListenerTrait.php:88
Stack trace:
#0 /.../vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/Legacy/TestListenerForV5.php(45): Mockery\Adapter\Phpunit\Legacy\TestListenerTrait->startTestSuite()
#1 /.../vendor/phpunit/phpunit/src/Framework/TestResult.php(359): Mockery\Adapter\Phpunit\Legacy\TestListenerForV5->startTestSuite(Object(PHPUnit_Framework_TestSuite))
#2 /.../vendor/phpunit/phpunit/src/Framework/TestSuite.php(666): PHPUnit_Framework_TestResult->startTestSuite(Object(PHPUnit_Framework_TestSuite))
#3 /.../vendor/phpunit/phpunit/src/TextUI/TestRunner.php(517): PHPUnit_Framework_TestSuite->run(Object(PHPUnit_Framework_TestResult))
#4 /.../vendor/phpunit/phpunit/src/TextUI/Command.php(186): PHPUnit_TextUI_TestRunner->doRun(Object(PHPUnit_Framework_TestSuite), Ar in /.../vendor/mockery/mockery/library/Mockery/Adapter/Phpunit/Legacy/TestListenerTrait.php on line 88
PHPUnit 5.7.27 by Sebastian Bergmann and contributors.
```

**Comment by rcwsr** [comment]
I think because this class _does_ exist:
`\PHPUnit\Framework\TestCase` in `vendor/phpunit/phpunit/src/ForwardCompatibility/TestCase.php`

**Comment by prisis** [comment]
can you show me the phpunit full version, from composer install output?

**Comment by prisis** [comment]
i need to change the if check... i will do it asap

**Comment by rcwsr** [comment]
```
        "name": "phpunit/phpunit",
        "version": "5.7.27",
        "version_normalized": "5.7.27.0",
```

```
        "name": "mockery/mockery",
        "version": "dev-master",
        "version_normalized": "9999999-dev",
```

**Pull request merged**
