### PR TITLE
Fix: array to string conversion in ConstantsPass [master]

### PR DESCRIPTION
**Pull request by MPC-khajiit**
Fix for #1084

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Is this bug in 1.3.x too? I think we should fix everything which can be reasonable fixed on there, and merge upwards.

**Comment by MPC-khajiit** [comment]
@GrahamCampbell in 1.3.x and 1.2.x too.

**Comment by GrahamCampbell** [comment]
Don't worry about 1.2.x, but if you could target 1.3.x, assuming @davedevelopment is happy with that, I think that'd be best. :)

**Comment by GrahamCampbell** [comment]
I\m a bit confused. This PR has actually already been applied to the code. Why is it being sent again?

**Comment by GrahamCampbell** [comment]
@davedevelopment This can be closed I think?

**Comment by MPC-khajiit** [comment]
@GrahamCampbell  @davedevelopment i'm closing it because previously i prepared two PR (for master and for 1.3 aka #1086) and was merged also into master.

**Comment by GrahamCampbell** [comment]
👍

**Pull request closed without merging**
