### PR TITLE
Add PhpStorm Advanced Metadata for autocompletion

### PR DESCRIPTION
**Pull request by alexdenvir**
I saw a previous attempt at this was made in #759, but it looks like @wan2land hasn't got around to creating a new PR based on the new format for PhpStorm metadata.

This PR is basically the same thing as #759, but using the new format.

For reference, [here is the documentation about this feature in PhpStorm](https://confluence.jetbrains.com/display/PhpStorm/PhpStorm+Advanced+Metadata)

### CODE REVIEW

**Comment by davedevelopment** [comment]
@robertbasic do you use PHPStorm by any chance? This looks fine to me, but another pair of eyes won't hurt.

**Comment by davedevelopment** [comment]
Thank you @alexdenvir  and @AndersonZacharyT :+1:

**Comment by Bilge** [comment]
This doesn't appear to have any effect. Do I have to do something to load it into PhpStorm? Instructions are unclear, but it seems to suggest it should require zero configuration.

**Comment by alexdenvir** [comment]
Still appears to work for me. I would suggest invalidating your IDE cache `File >>> Invalid Caches / Restart >>> Invalidate and Restart`

**Comment by Bilge** [comment]
Invalidating cache has no effect.

**Comment by jonnyynnoj** [comment]
@Bilge Unfortunately it breaks down when used with expectation chaining. If you assign the mock to a variable first `$mock = Mockery::mock(Connector::class);` you will get the metadata.

**Pull request merged**
