### PR TITLE
[1.4] Fix auto-generated return values with union types

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Same as https://github.com/mockery/mockery/pull/1143 for the 1.4 branch. Easier than dealing with those merge PRs.

---

Blocks https://github.com/laravel/framework/pull/38404. cc @davedevelopment, @driesvints.

### CODE REVIEW

**Comment by driesvints** [comment]
@davedevelopment definitely not want to pressure you (take your time) but this is the last thing we need to provide PHP 8.1 support in Laravel. Would be cool if we could merge and tag this soon! :)

**Comment by davedevelopment** [comment]
No worries, will tag shortly

**Comment by driesvints** [comment]
Thanks @davedevelopment! Appreciate it 👍

**Comment by driesvints** [comment]
I'm sorry @davedevelopment, seems like there are a couple of more snags to be solved before we have PHP 8.1 support in Laravel. But this PR definitely brought us closer so thank you!

**Comment by davedevelopment** [comment]
@driesvints no worries, good luck :)

**Pull request merged**
