### PR TITLE
Add support for target class attributes

### LINKED ISSUE #1209: Mocking undefined methods with PHP 8.2 fails
PHP 8.2 deprecates dynamic properties: https://www.php.net/manual/en/migration82.deprecated.php#migration82.deprecated.core.dynamic-properties

When Mockery creates a mock of an undefined method, the mock is empty, it does not have properties or methods. 

Under PHP 8.2 the following test will fail and throw an exception with the message "Creation of dynamic property Mockery_0__UndefinedClass::$foo is deprecated"

```php
namespace test\PHP82;

use Mockery\Adapter\Phpunit\MockeryTestCase;

class Php82LanguageFeaturesTest extends MockeryTestCase
{

    public function testCanMockUndefinedClasses()
    {
        $class = mock('UndefinedClass');

        $class->foo = 'bar';

        $this->assertSame('bar', $class->foo);
    }
}
```

The simplest fix for this issue would be to give undefined method mocks the `#[\AllowDynamicProperties]` attribute.

### PR DESCRIPTION
**Pull request by rneudorf-godaddy**
Resolves #1209.

This PR adds support for target class attributes. The `#[\AllowDynamicProperties]` attribute is the most straightfoward way to resolve PHP 8.2 compatibility issue mentioned in #1209.

### `TargetClassInterface` Update
- Added `getAttributes()` which returns an array of attributes
- Updated `DefinedTargetClass` to return an empty array.
- Updated `UndefinedTargetClass` to return `\AllowDynamicProperties` 👈 i.e. the fix

### Added `ClassAttributesPass`
- This pass inserts the attributes just before the class declaration.
- Updated `StringManipulationGenerator` to use this pass.

### Test Updates
- A few test were taking dynamically declaring properties in their mocks, updated those. 
- Added a test for `ClassAttributesPass`

### CODE REVIEW

**Review by thestalnakergroup — APPROVED** [review]
I'd love to be able to use this on a project I'm working on.

**Comment by unfulvio-godaddy** [comment]
@davedevelopment @GrahamCampbell  is this something that you would consider reviewing/merging? has tests

thank you

**Comment by davedevelopment** [comment]
> git pull git@github.com:rneudorf-godaddy/mockery.git 1209/add-support-for-class-attributes

Scratch that, hadn't pulled the branch down yet :rofl:

**Comment by ghostwriter** [comment]
Hi,

I just wanted to apologize for the delay in reviewing your pull request.

I'm going to rebase, finalize and merge this pull request to `1.5.x` branch.

Thanks for your patience and for your contribution to the project!

**Review by ghostwriter — COMMENTED** [review]
Target is `1.6.0` because we're adding new functionality in a backward-compatible manner.

**Comment by rneudorf-godaddy** [comment]
Thanks!

**Pull request merged**
