### PR TITLE
Fixed conflicting mock names

### PR DESCRIPTION
**Pull request by macdabby**
Fixes https://github.com/mockery/mockery/issues/768

PHPunit is not running ATM, investigating further.

### CODE REVIEW

**Comment by robertbasic** [comment]
Thanks @macdabby! Could you please add test cases that show that the bug is really fixed?

**Comment by macdabby** [comment]
Added tests, and ran them before the fix commit to ensure that they fail before and pass after.

**Comment by macdabby** [comment]
Bump - can i get a merge? Are there other changes needed?

**Comment by robertbasic** [comment]
Sorry, fell of the radar this week. I'll merge it over the weekend if Dave
doesn't beat me to it!

Thanks again for the work!

**Comment by macdabby** [comment]
sweet thanks!

**Comment by davedevelopment** [comment]
Looks good to me, thanks for your hard work on this.

**Pull request merged**
