### PR TITLE
1.0 release

### PR DESCRIPTION
**Pull request by davedevelopment**
Mockery is never going to be perfect and if I wait until I think we're ready for a 1.0 release, it'll never happen. So I'm going to tag 1.0 on Friday. 

Edit: This PR is a WIP, probably going to add bits too it throughout the week.

### CODE REVIEW

**Comment by robertbasic** [comment]
Are we going to continue support for HHVM? AFAIK lots of projects and libs dropped/are dropping support for it.

**Comment by davedevelopment** [comment]
@robertbasic good question and I don't know the answer for sure. My gut feeling is, we'll try for those already running it, but we can't guarantee anything for future. 

The HHVM team aren't going to follow PHP 7, so they're concentrating on Hack itself. -
 http://hhvm.com/blog/2017/09/18/the-future-of-hhvm.html.

**Comment by davedevelopment** [comment]
@robertbasic Oh and don't rush with the docs, don't let my hasty decision to push 1.0 out spoil your week :smile:

**Comment by robertbasic** [comment]
@davedevelopment nah, I have free time today/tomorrow after work so it's all good! And I owe those PRs for a long time now, so might as well just finally be done with them :)

**Comment by davedevelopment** [comment]
#793 and #794 need considering

**Pull request merged**
