### PR TITLE
composer.json: Allow PHP 8

### PR DESCRIPTION
**Pull request by serima**
Refs: https://github.com/sebastianbergmann/phpunit/issues/4325#issuecomment-650717242

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Mockery doesn't work at all on PHP 8 yet. This PR cannot be merged yet.

**Comment by GrahamCampbell** [comment]
Some stuff is in progress at https://github.com/mockery/mockery/pull/1072.

**Comment by GrahamCampbell** [comment]
If you'd like to help, fixing the failing tests in that PR I linked to would be ideal.

**Comment by GrahamCampbell** [comment]
I have made major progress with https://github.com/mockery/mockery/pull/1072, and it's ready for review now. 🎉

**Comment by davedevelopment** [comment]
Closing in favour of #1072, which we'll get merged in to master

**Pull request closed without merging**
