### PR TITLE
Apply fixes from StyleCI

### PR DESCRIPTION
**Pull request by nathane**
This pull request applies code style fixes from an analysis carried out by [StyleCI](https://github.styleci.io).

---

For more information, click [here](https://github.styleci.io/analyses/z4AxGn).

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
You don't need to be an admin to configure StyleCI. Just put a `.styleci.yml` config file in the repo.

**Comment by GrahamCampbell** [comment]
Looks like one already exists, actually: https://github.com/mockery/mockery/blob/master/.styleci.yml.

**Comment by GrahamCampbell** [comment]
Looks like this PR can be closed now?

**Comment by robertbasic** [comment]
Yup.

**Pull request closed without merging**
