### PR TITLE
WIP/RFC: Allow mocking classes that have allows and expects methods

### PR DESCRIPTION
**Pull request by davedevelopment**
Refs #861

I'm not too sure how I feel about this. The waters are already muddy as they are with the` Mockery::mock` method marked up as returning a `MockInterface`, this makes it as clear as mud.

# How it works

- I extracted everything in `MockInterface`, except for `allows` and `expects`, in to a new interface, ironically called `LegacyMockInterface`. `MockInterface` extends `LegacyMockInterface`
- All methods that previously returned a `MockInterface`, now might also return a `LegacyMockInterface`. 
- All methods that previously accepted a `MockInterface`, now accept a `LegacyMockInterface`
- If the generator detects that the target type has `allows` or `expects` methods, it downgrades the generated mock from a `MockInterface` to a `LegacyMockInterface`.

### CODE REVIEW

**Comment by sebastiaanluca** [comment]
Has this been merged into a release yet?

**Comment by elimentz** [comment]
@nathane @padraic How long until this gets merged? I have multiple projects that are blocked because of this, I can't run or write any tests any more!! Please see [this issue](https://github.com/laravel/framework/issues/21987) for more details

**Comment by davedevelopment** [comment]
I've requested a review from @robertbasic, I suggest we merge this if it fits ok with a view to tidying up for 2.0

**Comment by robertbasic** [comment]
@davedevelopment one small fix and it's good to go

**Comment by elimentz** [comment]
Thanks you guys!!

**Comment by davedevelopment** [comment]
@robertbasic what is the small fix? Am I not seeing something or is it a secret?

**Comment by robertbasic** [comment]
I thought I left a comment but apparently I need to press another button.

Screenshot_2019-04-26_13-53-51

**Comment by robertbasic** [comment]
@davedevelopment should be good to go if I pressed all the right buttons this time :D

**Comment by davedevelopment** [comment]
:+1:

**Comment by davedevelopment** [comment]
If someone gets 5 minutes to add something to the CHANGELOG (I always forget...), knock yourselves out :+1:

**Comment by krenor** [comment]
This isn't tagged yet, is it?

**Comment by lezhnev74** [comment]
Is it tagged?

**Comment by zipibz** [comment]
Echoing the two comments above, is this tagged @davedevelopment ?

Facing issues when trying to mock 
`Gate::allows($ability, $arguments)` 
using 
`Gate::shouldReceive('allows')->once()->andReturn(true)` in Laravel 

(same as [[5.5] Gate facade mock fails to mock out allows() method](https://github.com/laravel/framework/issues/21987))

**Comment by davedevelopment** [comment]
@krenor @lezhnev74 @zipibz just tagged now https://github.com/mockery/mockery/releases/tag/1.2.3

**Pull request merged**
