### PR TITLE
Fix license date

### PR DESCRIPTION
**Pull request by m1guelpf**
TO DO:

- [x] Wait to the next year (100% done, depends on timezone)
- [ ] Merge!

:octocat:

### CODE REVIEW

**Comment by PatrickRose** [comment]
Oh come on. People do this *every* year and it's pretty pointless...

On 31 Dec 2017 23:21, "Miguel Piedrafita" <notifications@github.com> wrote:

TO DO:

   - Wait to the next year (100% done, depends on timezone)
   - Merge!

[image: :octocat:]
------------------------------
You can view, comment on, or merge this pull request online at:

  https://github.com/mockery/mockery/pull/825
Commit Summary

   - Update license year

File Changes

   - *M* LICENSE <https://github.com/mockery/mockery/pull/825/files#diff-0>
   (2)

Patch Links:

   - https://github.com/mockery/mockery/pull/825.patch
   - https://github.com/mockery/mockery/pull/825.diff

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/mockery/mockery/pull/825>, or mute the thread

**Comment by m1guelpf** [comment]
@PatrickRose Better?

**Comment by GrahamCampbell** [comment]
Better to just write `2010`.

**Comment by m1guelpf** [comment]
@GrahamCampbell Done

**Pull request merged**
