### PR TITLE
first expectations are less specific than last

### PR DESCRIPTION
**Pull request by tflori**
a simple array_reverse can fix some tests at least in my case.

but it should be testet too. say me where I should write this test and I can write a test.

### CODE REVIEW

**Comment by tflori** [comment]
I already realized it breaks other things and working on it

**Comment by tflori** [comment]
why from master comes code with wrong code style? :-1:

**Comment by robertbasic** [comment]
Hey @tflori thanks for the PR, and I apologize that no one from the team took a look at it yet. I'm trying to fix that now.

Could you explain what's the original issue that you're trying to solve with this PR?

Thanks!

**Comment by tflori** [comment]
Hi, I don't remember which issue it was but at the end I solved my problems with `->byDefault()`.

Now that I know about by default I don't need it anymore but I still think that this order makes more sense.

**Comment by davedevelopment** [comment]
I think we'd need to do something more complex if we wanted this as a feature and it would need to make it's way to 2.0, so will close for now.

**Pull request closed without merging**
