### PR TITLE
Bugfix: 'Add support for ! to blacklist methods' for empty methods

### PR DESCRIPTION
**Pull request by lintaba**
it broke our tests:

```
ErrorException: Uninitialized string offset: 0

/var/www/html/src/vendor/sentry/sentry/lib/Raven/Breadcrumbs/ErrorHandler.php:34
/var/www/html/src/vendor/mockery/mockery/library/Mockery/Container.php:155
/var/www/html/src/vendor/mockery/mockery/library/Mockery.php:118
...
```

### CODE REVIEW

**Comment by mfn** [comment]
Oh noez, sorry for the break (I added the blacklist stuff).

I wonder though: would purpose has an **empty** `$partialMethod` in the first place? (wasn't aware of this)

They even get added to the "whitelist" (see line below).

Maybe line `152` should be placed not to return an array with empty elements in the first place?

From
```php
$partialMethods = explode(',', strtolower(rtrim($parts[1], ']')));
```
to
```php
$partialMethods = array_filter(explode(',', strtolower(rtrim($parts[1], ']'))));
```
🤷‍♀️

**Comment by lintaba** [comment]
yeah, even better, since in this case this would be still invoked:
```
$builder->addWhiteListedMethod( "" );
```

**Comment by mfn** [comment]
Yeah, I can't think of a use-case for that .. maybe just an unrealized side-effect of the code so far

**Comment by lintaba** [comment]
the behavioral difference may happen in `MockConfiguration::getMethodsToMock`. With blacklisted+whitelisted, it wont care about blacklisteds. My first fix also ignored blacklisted items (since whitelisted is `[""]`, which is not empty). The second fix however respects that, so if you blacklisted methods manually, and used the `Class[]` format, it will respect the blacklisted rules.

**Comment by davedevelopment** [comment]
Thanks all

**Comment by lintaba** [comment]
@davedevelopment (cc @mfn ), what do i need to do to make it part of a release? it still broke our tests :D

**Comment by davedevelopment** [comment]
@lintaba If you add a quick note for this in `CHANGELOG.md` in a PR, I'll tag next week.

**Comment by lintaba** [comment]
> @lintaba If you add a quick note for this in `CHANGELOG.md` in a PR, I'll tag next week.

https://github.com/mockery/mockery/pull/1010

**Comment by davedevelopment** [comment]
@lintaba thank you https://github.com/mockery/mockery/releases/tag/1.2.4

**Pull request merged**
